services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  streamlit:
    build:
      context: .
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    working_dir: /app
    command: streamlit run app/app.py --server.address 0.0.0.0 --server.port 8501 --server.runOnSave true
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - qdrant
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          ignore:
            - .venv
            - qdrant_data
            - __pycache__
            - .git
        - path: ./requirements.txt
          action: rebuild

configs:
  qdrant_config:
    content: |
      log_level: INFO